[package]
name = "machinglearing-gui"
version = "0.1.0"
description = "Local-first data and machine learning workspace"
authors = ["Kuroneko"]
edition = "2024"

[lib]
name = "machinglearing_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

